'use client';

import Link from 'next/link';
import { ArrowRight, Check, CheckCircle2, ChevronRight, FileCheck2, LockKeyhole, ShieldCheck } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { BrandMark, StatusBadge } from '@/components/veritas-ui';

const workflowStates = ['Opening public webpage', 'Capturing screenshot', 'Saving HTML snapshot', 'Generating manifest', 'Computing SHA-256 hashes', 'Integrity verified', 'Evidence record ready'];
const steps = [
  ['01', 'Add a public webpage', 'Choose a public HTTP or HTTPS page.', 'url'],
  ['02', 'Capture the page and artifacts', 'Save screenshot, HTML, headers, and metadata.', 'capture'],
  ['03', 'Generate integrity records', 'Create deterministic SHA-256 records for stored artifacts.', 'hash'],
  ['04', 'Verify and export', 'Recheck the artifacts and export a structured report.', 'verify'],
];
const useCases = {
  'Terms and policy monitoring': ['Track a public policy page over time.', 'Screenshot, HTML, headers, status, and manifest.', 'Text, metadata, and hash changes.', 'An evidence record with verification results and report export.'],
  'Pricing and product changes': ['Keep a dated record of a public price or product page.', 'Rendered page state plus source and response metadata.', 'Changed copy, final URL, status, and artifact hashes.', 'A report and bundle that keeps each capture independent.'],
  'Trademark and brand monitoring': ['Watch public pages where a brand or mark appears.', 'Page title, URL, screenshot, HTML, and selected headers.', 'Text additions/removals and metadata differences.', 'Stored artifacts that can be inspected and re-verified.'],
  'Public statement preservation': ['Preserve a public statement before it is edited or removed.', 'The page as captured, without relying on a later live recapture.', 'Differences between consecutive stored captures.', 'A readable preservation report with limitations.'],
  'Journalism and investigations': ['Create a repeatable record of public web material.', 'Capture context beyond a bare screenshot.', 'Observable content and response metadata changes.', 'Owner-scoped artifacts and integrity comparisons.'],
  'Compliance review': ['Review public pages against an internal process.', 'Artifact paths, metadata, headers, and hash records.', 'Differences across review captures.', 'A report generated from stored data, not a legal conclusion.'],
} as const;

type UseCase = keyof typeof useCases;

export default function HomePage() {
  const [heroStep, setHeroStep] = useState(workflowStates.length - 1);
  const [activeStep, setActiveStep] = useState(0);
  const [useCase, setUseCase] = useState<UseCase>('Terms and policy monitoring');
  const [reducedMotion, setReducedMotion] = useState(false);
  const stepRefs = useRef<Array<HTMLElement | null>>([]);

  useEffect(() => {
    const media = window.matchMedia('(prefers-reduced-motion: reduce)');
    const update = () => { setReducedMotion(media.matches); if (media.matches) setHeroStep(workflowStates.length - 1); };
    update();
    media.addEventListener('change', update);
    return () => media.removeEventListener('change', update);
  }, []);

  useEffect(() => {
    if (reducedMotion) return;
    let index = 0;
    const timer = window.setInterval(() => { index = (index + 1) % workflowStates.length; setHeroStep(index); }, 1350);
    return () => window.clearInterval(timer);
  }, [reducedMotion]);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { const index = stepRefs.current.indexOf(entry.target as HTMLElement); if (index >= 0) setActiveStep(index); } }), { threshold: 0.65 });
    stepRefs.current.forEach((element) => element && observer.observe(element));
    return () => observer.disconnect();
  }, []);

  return (
    <main className="min-h-screen overflow-hidden bg-[#070B14] text-slate-100">
      <header className="sticky top-0 z-20 border-b border-white/10 bg-[#070B14]/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><BrandMark /><nav className="flex items-center gap-3 text-sm"><Link href="/demo" className="hidden text-slate-300 hover:text-white sm:inline">View Demo</Link><Link href="/login" className="rounded-md border border-white/15 px-4 py-2 text-slate-200 hover:border-cyan-400/60">Sign in</Link><Link href="/register" className="rounded-md bg-cyan-400 px-4 py-2 font-semibold text-[#06111A] hover:bg-cyan-300">Start Free</Link></nav></div></header>

      <section className="relative border-b border-white/10"><div className="mx-auto grid max-w-6xl items-center gap-14 px-5 py-20 lg:grid-cols-[1fr_0.95fr] lg:px-8 lg:py-28"><div className="vw-reveal"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Evidence preservation workflow</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.05] tracking-tight text-white sm:text-6xl">Preserve web pages before they disappear.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Capture public web pages, preserve screenshot and HTML artifacts, verify cryptographic hashes, detect changes, and export structured evidence reports.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-md bg-cyan-400 px-5 py-3 font-semibold text-[#06111A] hover:bg-cyan-300">Start Free <ArrowRight className="h-4 w-4" /></Link><Link href="/demo" className="rounded-md border border-white/15 px-5 py-3 font-semibold hover:border-cyan-400/60">View Sample Evidence Record</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Private storage</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Owner-scoped records</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />SHA-256 checks</span></div></div><HeroWorkflow step={heroStep} state={workflowStates[heroStep]} /></div></section>

      <section className="border-b border-white/10 bg-[#0B1120]"><div className="mx-auto flex max-w-6xl flex-wrap gap-8 px-5 py-7 text-sm text-slate-300 lg:px-8"><span className="inline-flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-cyan-300" />Private artifact storage</span><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-300" />Cryptographic integrity</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-cyan-300" />Public demo is read-only</span><span className="ml-auto text-slate-500">Built for careful public-web workflows</span></div></section>

      <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="max-w-2xl vw-reveal"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">The problem</p><h2 className="mt-3 text-3xl font-semibold text-white sm:text-4xl">The page you need tomorrow may not look like the page you saw today.</h2><p className="mt-5 leading-7 text-slate-400">Websites can be edited, removed, redirected, or replaced. A normal screenshot often leaves out response context, source artifacts, and a repeatable way to check that saved files were not altered.</p></div></section>

      <section className="border-y border-white/10 bg-[#0B1120]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 lg:grid-cols-[0.7fr_1.3fr] lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">How it works</p><div className="mt-10 border-l border-cyan-400/25">{steps.map(([number, title, body], index) => <article key={number} ref={(element) => { stepRefs.current[index] = element; }} className={`relative py-5 pl-7 transition duration-500 ${activeStep === index ? 'opacity-100' : 'opacity-45'}`}><span className={`absolute -left-[13px] top-6 flex h-6 w-6 items-center justify-center rounded-full border text-xs font-semibold ${activeStep === index ? 'border-cyan-300 bg-cyan-400 text-[#06111A]' : 'border-slate-600 bg-[#0B1120] text-slate-500'}`}>{number}</span><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></article>)}</div></div><div className="lg:sticky lg:top-28 lg:h-fit"><WorkflowVisual step={activeStep} /></div></div></section>

      <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Core capabilities</p><h2 className="mt-3 text-3xl font-semibold text-white sm:text-4xl">Capture, compare, verify.</h2></div><div className="mt-12 space-y-5"><Capability number="01" title="Capture" body="Preserve the rendered page and its context in one server-side workflow." items={['Screenshot', 'HTML snapshot', 'Headers and metadata', 'Deterministic manifest']} tone="cyan" /><Capability number="02" title="Compare" body="See what changed between consecutive stored captures without executing captured HTML in the app." items={['Text additions and removals', 'Title, URL, and status changes', 'Selected header changes', 'Bounded change signal']} tone="violet" reverse /><Capability number="03" title="Verify" body="Recompute stored artifact hashes and export a readable evidence preservation report or bundle." items={['Screenshot hash', 'HTML hash', 'Manifest hash', 'Report and ZIP bundle']} tone="green" /></div><div className="mt-8 flex flex-wrap gap-3 text-sm text-slate-400"><span>Scheduled monitoring</span><span>·</span><span>Private storage</span><span>·</span><span>Owner-scoped access</span><span>·</span><span>Evidence reports</span></div></section>

      <section className="border-y border-white/10 bg-[#0B1120]"><div className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.55fr_1.45fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Use cases</p><h2 className="mt-3 text-3xl font-semibold text-white">A focused record for the page in front of you.</h2><div className="mt-8 space-y-2">{Object.keys(useCases).map((item) => <button key={item} type="button" aria-pressed={useCase === item} onClick={() => setUseCase(item as UseCase)} className={`flex w-full items-center justify-between border-b border-white/10 py-3 text-left text-sm transition ${useCase === item ? 'text-cyan-300' : 'text-slate-400 hover:text-white'}`}><span>{item}</span><ChevronRight className={`h-4 w-4 transition ${useCase === item ? 'translate-x-1' : ''}`} /></button>)}</div></div><div className="flex items-center"><div className="w-full rounded-xl border border-cyan-400/20 bg-[#101B2C] p-6 shadow-xl shadow-cyan-950/20 sm:p-8"><p className="text-xs uppercase tracking-widest text-slate-500">{useCase}</p><h3 className="mt-4 text-2xl font-semibold text-white">{useCases[useCase][0]}</h3><div className="mt-8 grid gap-5 sm:grid-cols-3"><Info label="Captures" value={useCases[useCase][1]} /><Info label="Detects" value={useCases[useCase][2]} /><Info label="Contains" value={useCases[useCase][3]} /></div></div></div></div></div></section>

      <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Sample evidence record</p><h2 className="mt-3 text-3xl font-semibold text-white">Inspect the workflow before you create an account.</h2><p className="mt-4 leading-7 text-slate-400">The public demo uses bundled IANA sample artifacts. It never reads private Supabase data or calls a user verification route.</p><Link href="/demo" className="mt-7 inline-flex items-center gap-2 rounded-md bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-[#06111A] hover:bg-cyan-300">Open Demo <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-xl border border-white/10 bg-[#0E1929] p-4"><div className="flex items-center justify-between border-b border-white/10 pb-3"><span className="text-sm font-semibold text-slate-100">IANA-managed Reserved Domains</span><StatusBadge tone="success">Integrity Verified</StatusBadge></div><img src="/demo/iana-screenshot.png" alt="IANA reserved domains sample record preview" className="mt-4 max-h-72 w-full rounded-md object-cover object-top" /><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span className="rounded border border-white/10 p-2 text-slate-400">200 OK</span><span className="rounded border border-white/10 p-2 text-slate-400">3 artifacts</span><span className="rounded border border-white/10 p-2 text-emerald-300">Hashes match</span></div></div></div></section>

      <section className="border-y border-white/10 bg-[#0B1120]"><div className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div className="rounded-xl border border-white/10 bg-[#F7F7FA] p-4 shadow-xl"><div className="rounded border border-slate-200 bg-white p-4"><div className="flex items-center justify-between border-b border-slate-200 pb-3"><span className="text-sm font-bold text-slate-900">VeritasWeb</span><span className="rounded bg-emerald-100 px-2 py-1 text-[10px] font-semibold text-emerald-700">INTEGRITY VERIFIED</span></div><div className="mt-5 text-center text-sm font-semibold text-slate-900">Evidence Preservation Report</div><div className="mt-5 grid grid-cols-3 gap-2"><span className="h-14 rounded bg-slate-100" /><span className="h-14 rounded bg-slate-100" /><span className="h-14 rounded bg-slate-100" /></div><div className="mt-5 space-y-2"><span className="block h-2 w-4/5 rounded bg-slate-200" /><span className="block h-2 w-3/5 rounded bg-slate-200" /><span className="block h-2 w-2/5 rounded bg-slate-200" /></div></div></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Sample report</p><h2 className="mt-3 text-3xl font-semibold text-white">A printable record built from stored data.</h2><p className="mt-4 leading-7 text-slate-400">Reports keep the verification table, screenshot, paths, headers, timestamps, and limitations readable across as many pages as the data requires.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/demo" className="rounded-md border border-white/15 px-4 py-2.5 text-sm font-semibold text-slate-100 hover:border-cyan-400/60">Preview Sample Report</Link><a href="/demo/sample-report.pdf" download className="rounded-md bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-[#06111A] hover:bg-cyan-300">Download Sample PDF</a></div></div></div></div></section>

      <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Security and limitations</p><h2 className="mt-3 text-3xl font-semibold text-white">Strong technical checks, honest boundaries.</h2></div><div className="space-y-4 text-sm leading-6 text-slate-400"><p className="flex gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-emerald-400" />Private artifact storage, owner-scoped records, server-side signed URLs, and SSRF protection.</p><p className="flex gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-emerald-400" />Cryptographic checks confirm whether stored artifacts match their recorded hashes.</p><p className="border-l border-amber-400/50 pl-4 text-slate-500">VeritasWeb verifies stored artifact integrity. It does not independently establish legal admissibility and does not replace formal chain-of-custody, notarization, expert review, or jurisdiction-specific procedures.</p></div></div></section>

      <section className="border-y border-white/10 bg-[#0B1120]"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 px-5 py-16 lg:flex-row lg:items-center lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Start preserving web records.</p><h2 className="mt-3 text-3xl font-semibold text-white">See the workflow, then make it yours.</h2></div><div className="flex flex-wrap gap-3"><Link href="/register" className="rounded-md bg-cyan-400 px-5 py-3 font-semibold text-[#06111A] hover:bg-cyan-300">Create Free Account</Link><Link href="/demo" className="rounded-md border border-white/15 px-5 py-3 font-semibold text-slate-100 hover:border-cyan-400/60">View Demo</Link></div></div></section>
      <footer className="mx-auto max-w-6xl px-5 py-8 text-xs leading-6 text-slate-500 lg:px-8">Generated by VeritasWeb as a forensic-style web capture workflow. Consult legal counsel for jurisdiction-specific evidence procedures.</footer>
    </main>
  );
}

function HeroWorkflow({ step, state }: { step: number; state: string }) {
  return <div className="rounded-xl border border-cyan-400/20 bg-[#0B1423] p-4 shadow-2xl shadow-cyan-950/30"><div className="rounded-lg border border-white/10 bg-[#0E1929] p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-2 text-sm font-semibold"><FileCheck2 className="h-4 w-4 text-cyan-300" />Evidence workflow</div><span className={`text-xs font-medium ${step >= 5 ? 'text-emerald-300' : 'text-cyan-300'}`}>{state}</span></div><div className="relative mt-5 h-36 overflow-hidden rounded-md border border-cyan-400/20 bg-[linear-gradient(135deg,#12233a,#081121)] p-5"><div className="h-2 w-24 rounded bg-cyan-400/70" /><div className="mt-7 h-3 w-3/4 rounded bg-white/20" /><div className="mt-3 h-3 w-1/2 rounded bg-white/10" />{step > 0 && <span className="vw-scan-line" aria-hidden="true" />}</div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><Mini label="Screenshot" active={step >= 1} /><Mini label="HTML" active={step >= 2} /><Mini label="Manifest" active={step >= 3} /></div><div className="mt-4 rounded-md border border-white/10 bg-[#081121] p-3 font-mono text-xs text-slate-400"><span className="text-cyan-300">sha256</span> {step >= 4 ? 'ef479e19a7bdd19e...d9ee3d' : 'computing...'}</div><div className={`mt-4 flex items-center justify-between rounded-md border px-3 py-2 text-sm ${step >= 5 ? 'border-emerald-400/30 bg-emerald-400/10 text-emerald-300' : 'border-white/10 text-slate-500'}`}><span>{step >= 5 ? 'All artifact hashes match' : 'Awaiting integrity check'}</span>{step >= 5 && <CheckCircle2 className="h-4 w-4" />}</div></div></div>;
}

function Mini({ label, active }: { label: string; active: boolean }) { return <div className={`rounded-md border p-3 ${active ? 'border-cyan-400/40 bg-cyan-400/10 text-cyan-200' : 'border-white/10 text-slate-500'}`}>{label}<span className="mt-1 block text-[10px]">{active ? 'stored' : 'pending'}</span></div>; }
function WorkflowVisual({ step }: { step: number }) { return <div className="rounded-xl border border-cyan-400/20 bg-[#101B2C] p-5 shadow-xl shadow-cyan-950/20"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-widest text-slate-500">Live workflow preview</span><span className="font-mono text-xs text-cyan-300">0{step + 1}/04</span></div><div className="mt-5 rounded-lg border border-white/10 bg-[#081121] p-5"><div className="h-2 w-20 rounded bg-cyan-400/70" /><div className="mt-7 h-3 w-4/5 rounded bg-white/20" /><div className="mt-3 h-3 w-3/5 rounded bg-white/10" /><div className="mt-8 grid grid-cols-3 gap-2"><span className={`h-10 rounded border ${step >= 1 ? 'border-cyan-400/40 bg-cyan-400/10' : 'border-white/10'}`} /><span className={`h-10 rounded border ${step >= 2 ? 'border-cyan-400/40 bg-cyan-400/10' : 'border-white/10'}`} /><span className={`h-10 rounded border ${step >= 3 ? 'border-emerald-400/40 bg-emerald-400/10' : 'border-white/10'}`} /></div></div><p className="mt-4 text-sm leading-6 text-slate-400">{steps[step][2]}</p></div>; }
function Capability({ number, title, body, items, tone, reverse = false }: { number: string; title: string; body: string; items: string[]; tone: 'cyan' | 'violet' | 'green'; reverse?: boolean }) { const colors = { cyan: 'border-cyan-400/30 bg-cyan-400/5 text-cyan-300', violet: 'border-violet-400/30 bg-violet-400/5 text-violet-300', green: 'border-emerald-400/30 bg-emerald-400/5 text-emerald-300' }; return <article className={`grid gap-8 rounded-xl border p-6 sm:p-8 lg:grid-cols-[0.5fr_1.5fr] ${colors[tone]} ${reverse ? 'lg:grid-cols-[1.5fr_0.5fr]' : ''}`}><div className={reverse ? 'lg:order-2' : ''}><span className="font-mono text-sm">{number}</span><h3 className="mt-3 text-3xl font-semibold text-white">{title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">{body}</p></div><div className={`grid gap-3 sm:grid-cols-2 ${reverse ? 'lg:order-1' : ''}`}>{items.map((item) => <div key={item} className="flex items-center gap-2 rounded-md border border-white/10 bg-[#0B1120]/60 p-3 text-sm text-slate-200"><Check className="h-4 w-4 shrink-0" />{item}</div>)}</div></article>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="border-l border-cyan-400/30 pl-4"><p className="text-xs uppercase tracking-widest text-slate-500">{label}</p><p className="mt-2 text-sm leading-6 text-slate-300">{value}</p></div>; }
