import { jsPDF } from 'jspdf';
import {
  getCaptureManifestHash,
  getCaptureMonitor,
  getCaptureScreenshotPath,
  type OwnedCaptureRecord,
} from '@/lib/captures';
import type { CaptureVerificationResult } from '@/lib/verification';

if (typeof globalThis.navigator === 'undefined') {
  Object.defineProperty(globalThis, 'navigator', {
    value: { userAgent: 'node' },
    writable: true,
  });
}

type ReportInput = {
  capture: OwnedCaptureRecord;
  verification: CaptureVerificationResult;
  generatedAt: string;
};

const IMPORTANT_HEADERS = [
  'content-type',
  'last-modified',
  'etag',
  'cache-control',
  'date',
  'server',
];

function stringifyValue(value: unknown) {
  if (value === null || value === undefined || value === '') {
    return 'Not recorded';
  }

  if (typeof value === 'string') {
    return value;
  }

  return JSON.stringify(value);
}

function headersObject(headers: unknown) {
  if (
    !headers ||
    typeof headers !== 'object' ||
    Array.isArray(headers)
  ) {
    return {};
  }

  return Object.entries(headers).reduce<
    Record<string, unknown>
  >((result, [key, value]) => {
    result[key.toLowerCase()] = value;
    return result;
  }, {});
}

export function generateCaptureReportPdf({
  capture,
  verification,
  generatedAt,
}: ReportInput) {
  const pdf = new jsPDF({
    unit: 'pt',
    format: 'a4',
  });

  const margin = 48;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (height: number) => {
    if (y + height > pageHeight - margin) {
      pdf.addPage();
      y = margin;
    }
  };

  const addText = (
    text: string,
    options?: {
      size?: number;
      style?: 'normal' | 'bold';
      gap?: number;
    }
  ) => {
    const size = options?.size ?? 10;
    pdf.setFont('helvetica', options?.style ?? 'normal');
    pdf.setFontSize(size);

    const lines = pdf.splitTextToSize(text, contentWidth);
    ensureSpace(lines.length * (size + 4));
    pdf.text(lines, margin, y);
    y += lines.length * (size + 4) + (options?.gap ?? 4);
  };

  const addSection = (title: string) => {
    ensureSpace(34);
    y += 8;
    pdf.setDrawColor(180);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 18;
    addText(title, {
      size: 13,
      style: 'bold',
      gap: 8,
    });
  };

  const addField = (label: string, value: unknown) => {
    addText(`${label}: ${stringifyValue(value)}`, {
      size: 9,
      gap: 2,
    });
  };

  const monitor = getCaptureMonitor(capture);
  const screenshotPath = getCaptureScreenshotPath(capture);
  const manifestHash = getCaptureManifestHash(capture);
  const headers = headersObject(capture.headers);
  const importantHeaders = IMPORTANT_HEADERS.reduce<
    Record<string, unknown>
  >((result, header) => {
    if (headers[header] !== undefined) {
      result[header] = headers[header];
    }
    return result;
  }, {});

  let screenshotIncluded = false;
  let screenshotEmbedReason = 'No screenshot artifact available.';

  pdf.setTextColor(30);
  addText('VeritasWeb Evidence Preservation Report', {
    size: 18,
    style: 'bold',
    gap: 10,
  });
  addText(
    'Generated from stored capture data. This report is an evidence preservation summary, not a legal admissibility guarantee.',
    { size: 10, gap: 12 }
  );

  addSection('1. Report Metadata');
  addField('Report generated at', generatedAt);
  addField('Generated by', 'VeritasWeb');
  addField('Report type', 'Evidence Preservation Report');
  addField('Source', 'Stored capture data');

  addSection('2. Capture Summary');
  addField('Capture ID', capture.id);
  addField('Monitor ID', capture.monitor_id);
  addField('Monitor URL', monitor?.url);
  addField('Capture status', capture.capture_status);
  addField('Captured at', capture.captured_at ?? capture.timestamp);
  addField('Original URL', capture.original_url);
  addField('Final URL', capture.final_url);
  addField('Page title', capture.page_title);
  addField('HTTP status code', capture.status_code);

  addSection('3. Evidence Artifacts');
  addField('Screenshot storage path', screenshotPath);
  addField('HTML storage path', capture.html_path);
  addField('HTML artifact stored', capture.html_path ? 'yes' : 'no');

  if (verification.artifacts?.screenshotBuffer) {
    try {
      const imageData = `data:image/png;base64,${verification.artifacts.screenshotBuffer.toString('base64')}`;
      const imageProperties =
        pdf.getImageProperties(imageData);
      const imageWidth = contentWidth;
      const imageHeight =
        (imageProperties.height * imageWidth) /
        imageProperties.width;
      const displayHeight = Math.min(imageHeight, 300);

      ensureSpace(displayHeight + 28);
      addField('Screenshot included', 'yes');
      pdf.addImage(
        imageData,
        'PNG',
        margin,
        y,
        imageWidth,
        displayHeight
      );
      y += displayHeight + 8;
      screenshotIncluded = true;
      screenshotEmbedReason = '';
    } catch (error) {
      console.error('[pdf-report:screenshot]', error);
      screenshotEmbedReason =
        'Screenshot artifact could not be embedded.';
    }
  }

  if (!screenshotIncluded) {
    addField('Screenshot included', 'no');
    addField('Reason', screenshotEmbedReason);
  }

  addSection('4. Integrity Hashes');
  addField('Screenshot SHA-256', capture.screenshot_sha256);
  addField('HTML SHA-256', capture.html_sha256);
  addField('Manifest SHA-256', manifestHash);
  addField('Previous capture hash', capture.previous_capture_hash);

  addSection('5. Verification Result');
  addField('Verification status', verification.status);
  addField('Verified at', verification.verifiedAt);
  addField(
    'Screenshot hash match',
    verification.checks.screenshot?.match ?? 'not available'
  );
  addField(
    'HTML hash match',
    verification.checks.html?.match ?? 'not available'
  );
  addField(
    'Manifest hash match',
    verification.checks.manifest?.match ?? 'not available'
  );
  addField('Verification message', verification.message);

  addSection('6. HTTP Response Metadata');
  addField('Status code', capture.status_code);
  addText('Important headers:', {
    size: 9,
    style: 'bold',
  });
  addText(JSON.stringify(importantHeaders, null, 2), {
    size: 8,
  });
  addText('Full response headers:', {
    size: 9,
    style: 'bold',
  });
  addText(JSON.stringify(headers, null, 2), {
    size: 8,
  });

  addSection('7. Limitations');
  [
    'This report verifies that stored artifacts match their recorded hashes and deterministic manifest metadata.',
    'This report does not independently prove legal admissibility.',
    'This report does not replace formal chain-of-custody, notarization, or jurisdiction-specific evidence procedures.',
    'Website content may vary by geography, authentication state, cookies, scripts, browser behavior, or time.',
    'The report is generated from stored artifacts and metadata; it does not recapture the website.',
  ].forEach((item) => addText(`- ${item}`, { size: 9 }));

  const pageCount = pdf.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    pdf.setPage(page);
    pdf.setFontSize(8);
    pdf.setTextColor(120);
    pdf.text(
      `VeritasWeb Evidence Preservation Report - Page ${page} of ${pageCount}`,
      margin,
      pageHeight - 24
    );
  }

  return Buffer.from(pdf.output('arraybuffer'));
}
